#!/usr/bin/env python3
"""Generate Clash and Surge rule sets from the canonical endpoint list."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


HOST_RE = re.compile(
    r"^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+"
    r"[a-z]{2,63}$",
    re.IGNORECASE,
)
ROUTES = ("direct", "proxy")


def load_entries(source: Path) -> dict[str, list[dict[str, object]]]:
    data = json.loads(source.read_text(encoding="utf-8"))
    entries = data.get("entries")
    if not isinstance(entries, list):
        raise ValueError("data/emby-endpoints.json must contain an entries array")

    grouped: dict[str, list[dict[str, object]]] = {route: [] for route in ROUTES}
    seen: dict[str, str] = {}
    for index, entry in enumerate(entries, start=1):
        if not isinstance(entry, dict):
            raise ValueError(f"entry {index} is not an object")
        route = entry.get("route")
        host = entry.get("host")
        port = entry.get("port")
        if route not in ROUTES:
            raise ValueError(f"entry {index} has unsupported route: {route!r}")
        if not isinstance(host, str) or not HOST_RE.fullmatch(host):
            raise ValueError(f"entry {index} has invalid host: {host!r}")
        if not isinstance(port, int) or not 1 <= port <= 65535:
            raise ValueError(f"entry {index} has invalid port: {port!r}")
        normalized_host = host.lower()
        if normalized_host in seen:
            raise ValueError(
                f"host appears more than once: {normalized_host} "
                f"({seen[normalized_host]} and {route})"
            )
        seen[normalized_host] = route
        grouped[route].append({**entry, "host": normalized_host})
    return grouped


def render_yaml(entries: list[dict[str, object]]) -> str:
    lines = [
        "# Generated by scripts/build_rules.py. Do not edit by hand.",
        "payload:",
    ]
    lines.extend(f'  - "DOMAIN,{entry["host"]}"' for entry in entries)
    return "\n".join(lines) + "\n"


def render_surge(entries: list[dict[str, object]]) -> str:
    lines = [
        "# Generated by scripts/build_rules.py. Do not edit by hand.",
    ]
    lines.extend(f"DOMAIN,{entry['host']}" for entry in entries)
    return "\n".join(lines) + "\n"


def write_or_check(path: Path, content: str, check: bool) -> bool:
    if check:
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            print(f"out of date: {path.as_posix()}")
            return False
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    print(f"wrote {path.as_posix()}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    root = Path(__file__).resolve().parents[1]
    grouped = load_entries(root / "data" / "emby-endpoints.json")
    outputs = {
        root / "rules" / "clash" / "emby-direct.yaml": render_yaml(grouped["direct"]),
        root / "rules" / "clash" / "emby-proxy.yaml": render_yaml(grouped["proxy"]),
        root / "rules" / "surge" / "emby-direct.list": render_surge(grouped["direct"]),
        root / "rules" / "surge" / "emby-proxy.list": render_surge(grouped["proxy"]),
    }

    ok = all(write_or_check(path, content, args.check) for path, content in outputs.items())
    if args.check:
        print("rule files are up to date" if ok else "rule files need regeneration")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
